### ISSUE TITLE
Use with macro that generates a block

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_await#10]
``` haxe
@:await
class Main
{

    @:await static function main()
    {
        var b = @:await bool();
        trace(b);
        Macro.tryCatch({
          var i = int();
          i *= i;
          trace(i);
        });
    }

    @:async static function bool() return true;
    static function int() return 1;
}

class Macro {
    public static macro function tryCatch(e:haxe.macro.Expr) {
        return macro try $e catch(e:Dynamic) trace(e);
    }
}
```

The above code outputs something like this:

``` js
console.log(__t0_result);
var i = Main["int"]();
i *= i;
try {
    console.log(i);
} catch( e ) {
    if (e instanceof js__$Boot_HaxeError) e = e.val;
    console.log(e);
}
```

Note that `var i = Main.int(); i *= i;` got moved out of the try block, I think that shouldn't happen.

**Comment by benmerckx** [comment]
Thanks for the example, I'll have a look at it. It could be fairly complex, or simply the way I handle blocks, can't tell at this time.

**Comment by benmerckx** [comment]
This should work with the last update. No processing is done on blocks that do not contain @:await or @:async. This will fix this issue, but will fail if you're using @:await inside of `Macro.tryCatch`. There's not much I can do to fix that. I've tried running those expression macros before transforming, but I can't find a reliable way to do so and the haxe docs are clear that the build order is unspecified and shouldn't be relied on.

**Comment by kevinresol** [comment]
This seem to work for now. Thanks!
