### ISSUE TITLE
Some problem with haxe 4?

### ISSUE THREAD

**Issue by ciscoheat** [haxetink/tink_await#18]
Hi, I have noticed some problem on the development build on Travis with tink_await:

https://travis-ci.org/ciscoheat/buddy/jobs/298614112#L452

```
/home/travis/haxe/lib/tink_await/0,2,0/src/tink/await/AsyncField.hx:105: characters 74-79 : Unexpected final
```

**Comment by benmerckx** [comment]
This should have been fixed in 575692d1a75e96c630ec966bbf5939785b774a24, but wasn't released on haxelib. I put out a 0.3.0 release.
