### ISSUE TITLE
does not compile with actual haxe 

### ISSUE THREAD

**Issue by AdrianV** [haxetink/tink_await#23]
Is broken since haxe_2018-06-06_development_252bb32
fails with:

C:\haxe\lib\tink_await/git/src/tink/await/AsyncField.hx:457: characters 11-39 : tink.await.Thunk<haxe.macro.Expr> has no field func
C:\haxe\lib\tink_await/git/src/tink/await/AsyncField.hx:353: characters 16-50 : tink.await.Thunk<haxe.macro.Expr> has no field at
C:\haxe\lib\tink_await/git/src/tink/await/AsyncField.hx:355: characters 20-63 : tink.await.Thunk<haxe.macro.Expr> has no field at
C:\haxe\lib\tink_await/git/src/tink/await/AsyncField.hx:361: characters 8-42 : tink.await.Thunk<haxe.macro.Expr> has no field at
C:\haxe\lib\tink_await/git/src/tink/await/AsyncField.hx:362: characters 16-57 : tink.await.Thunk<haxe.macro.Expr> has no field at

**Comment by AdrianV** [comment]
latest working build was haxe_2018-06-06_development_bcea7ec

**Comment by AdrianV** [comment]
When I type each expression in these locations explicitly to Expr it compiles now. Do you want a pull request for that ?

**Comment by benmerckx** [comment]
Thanks for investigating! Please do submit a PR :)

**Comment by AdrianV** [comment]
#24
