### ISSUE TITLE
Don't work with Haxe 4 preview 5

### ISSUE THREAD

**Issue by posxposy** [haxetink/tink_await#28]
Hi there, 
`tink_await` works for me fine with Haxe 4 preview 4, but won't compiling with preview 5.  Even if I just add it as a lib to the project without any use of it (`-dce full` enabled).
Here is an errors:
```
C:\HaxeToolkit\haxe\lib\tink_await/0,4,0/src/tink/await/Await.hx:10: lines 10-88 : Defined in this class
C:\HaxeToolkit\haxe\lib\tink_syntaxhub/0,3,6/src/tink/SyntaxHub.hx:27: characters 5-31 : Class<tink.syntaxhub.FrontendContext> has no field resetCache
C:\HaxeToolkit\haxe\lib\tink_syntaxhub/0,3,6/src/tink/SyntaxHub.hx:28: characters 28-52 : Class<tink.syntaxhub.FrontendContext> has no field findType
```

**Comment by kevinresol** [comment]
you should update `tink_syntaxhub` to latest git version

**Comment by posxposy** [comment]
Got it, thanks. Any plans for a release with latest changes from git version?

**Comment by kevinresol** [comment]
follow up in https://github.com/haxetink/tink_syntaxhub/issues/10
