### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by darmie** [haxetink/tink_await#35]
I am using Haxe version 4.0 rc.5

I can't compile this code.

Code:
```hx
function writeFuncType(t:FunctionSig) {
	try {
		if (t.paramTypes.length != 0)
			writeString(" (param");
		for (p in t.paramTypes) {
			writeString(" ");
			writeString(p);
		}
		writeString(")");

		if (t.returnTypes.length != 0)
			writeString(" (return");
		for (r in t.returnTypes) {
			writeString(" ");
			writeString(r);
		}
		writeString(")");
		return Future.sync(true);
	} catch (e:Dynamic) {
		throw e;
	}
}

@async function writeFuncSignature(t:FunctionSig) {
	this.writeString("(func");
	@await writeFuncType(t);
        this.writeString(")");
}
```

Error:
`../tink/await/AsyncField.hx:470: characters 27-39 : String should be Null<haxe.macro.FunctionKind>`

**Comment by kevinresol** [comment]
Please post a complete and self-contained snippet

**Comment by benmerckx** [comment]
This seems like a user code error without a proper position. Are you using tink_await from git?

**Comment by darmie** [comment]
@kevinresol self-contained how?

@benmerckx I am using the haxelib version.

**Comment by darmie** [comment]
@kevinresol the recent git update fixed it. Thanks

**Comment by francescoagati** [comment]
i have this problem with haxe 4.0 (last release) and tink_await (git version)  maybe i must update some other tink dependency?

**Comment by CrazyFlasher** [comment]
Have the same error, if I includelibrary
-lib hexinject (just add it in build command together with -lib tink_await)

"hexinject": "git:https://github.com/CrazyFlasher/hexInject.git#73b59e0dccc6f181f3858ff7ee441283345abb1c"

https://github.com/CrazyFlasher/domwires-haxe

**Comment by CrazyFlasher** [comment]
funny, but it works if I put tink_await befor hexinject

```
//compiles
-lib tink_await
-lib hexinject

//doesn't compile
-lib hexinject
-lib tink_await
```
