### ISSUE TITLE
Warning : use Future.irreversible() - or better yet: new Future()

### ISSUE THREAD

**Issue by sonygod** [haxetink/tink_await#40]
Warning : use Future.irreversible() - or better yet: new Future()

	@async
	function test() {
		
		var p =cast  @await getUserInfo(12, "", null);

	
	}

![image](https://user-images.githubusercontent.com/748320/90864329-0f1e6700-e3c3-11ea-9661-d6312762ea2a.png)

![image](https://user-images.githubusercontent.com/748320/90864345-13e31b00-e3c3-11ea-876b-b978c97513d7.png)

how to improve code and fixed that Warning?

**Comment by AdrianV** [comment]
yes please - currently I remove the warning from tink because output is full of this warning and readability in VSCode is awful

**Comment by Jens-G** [comment]
Great! Any possibility to get that released to haxelib? Just asking, keep up the good work!
